### ISSUE TITLE
mp::filter::AuthSimple::config_targetRegister(), filter_auth_simple.cpp

### ISSUE THREAD

**Issue by textbrowser** [indexdata/metaproxy#14]
Please add fclose(fp) upon exiting the method.

**Comment by adamdickmeiss** [comment]
Seems like there is a general issue with this function - FILE* being a naked ptr so things will leak when exceptions are thrown etc.

**Comment by textbrowser** [comment]
Yes, exceptions too. Perhaps you can replace it with a safer C++ alternative?
