### ISSUE TITLE
SRU query response's recordSchema element is not standards compliant

### ISSUE THREAD

**Issue by gandaro** [indexdata/metaproxy#17]
When querying an SRU server that runs Metaproxy using the `searchRetrieve` operation, the response's `recordSchema` element simply mirrors the string that is provided by the client. If the client does not provide the `recordSchema` parameter, the element is empty.

---

**Example:**

Request:

`?version=1.1&operation=searchRetrieve&query=dinosaur`

Response:

```xml
...
  <zs:record>
    <zs:recordSchema/>
    ...
  </zs:record>
...
```

---

But according to the SRU standard, the `recordSchema` element must contain the URI of the used XML schema. There is a webpage listing [SRU Record Schemas](http://www.loc.gov/standards/sru/recordSchemas/), although their use of the `info:` URI scheme may be outdated.

This is what the [SRU specification](http://docs.oasis-open.org/search-ws/searchRetrieve/v1.0/os/part2-sru1.2/searchRetrieve-v1.0-os-part2-sru1.2.html#_Toc313357186) (same in 1.1, 1.2, and 2.0) states with respect to the allowed values of the `recordSchema` element in a server response:

> Mandatory. The URI identifier of the XML schema in which the record is encoded. Although the request may use the server's assigned short name, the response must always be the full URI.

From my cursory search the following may be the line of code that is responsible for providing the `recordSchema` for the response, but I am not sure:

https://github.com/indexdata/metaproxy/blob/52271477df4a80d2a2864ccad2ec6839a8defa6b/src/filter_sru_to_z3950.cpp#L885

I tested this by accessing the Library of Congress SRU server that runs Metaproxy 1.15.0.

**Comment by adamdickmeiss** [comment]
True, but very difficult to fix since Z39.50 does not, for each response record, carry the schema used. We have the record .. which is XML syntax and that's it! Therefore the MP sru filter does the best it can.. return whatever the client asked for .. that is a carried through in the conversion and so if that is honored, that would be the true -- short or full.
